version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    env_file: ./.env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  identity-recog-api:
    stdin_open: true
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    build: .
    image: hrithwikb/bitespeed
    container_name: identity-recog-api
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    restart: always

volumes:
  postgres-data: